##############################################################################################
################### EFFECT OF taVNS ON PUPIL SIZE - A BAYESIAN META-ANALYSIS #################
##############################################################################################

################### Shiny App v.1 15.12.2023 UI ##############################################

# Load required packages and source helper functions #----
library(shiny)
library(bayesmeta)
library(cowplot)
library(dplyr)
library(forcats)
library(DT)
library(data.table)
library(esc)
library(ggplot2)
library(MAd)
library(readr)
library(R.rsp)
library(shinyBS)
library(shinycssloaders)
library(shinythemes)
library(stringr)
library(tidyr)
library(xtable)
library(metaBMA)

#setwd("D:/SynologyDrive/BON_general/SynologyDrive/Paper/Drafts/pulsedtaVNS_pupil_meta/code")
#setwd("Y:/Paper/Drafts/pulsedtaVNS_pupil_meta/code")
#setwd("/Users/lisa/Desktop/code_tVNS_pupil_meta")
#setwd(LUISA DIRECTORY)

#source("D:/SynologyDrive/Paper/Drafts/pulsedtaVNS_pupil_meta/code/HelperFunctions.R")
#source("Y:/Paper/Drafts/pulsedtaVNS_pupil_meta/code/HelperFunctions.R")
#source("/Users/lisa/Desktop/code_tVNS_pupil_meta/HelperFunctions.R")
source("HelperFunctions.R")

#setwd(LUISA DIRECTORY)

#----
# Define UI
ui <- fluidPage(theme = shinytheme("readable"),
                titlePanel(title = div("taVNS and pupil dilation - a Bayesian living & interactive meta-analysis", 
                                       img(src='UKB.png',style="width: 50px", align = "right")),
                           windowTitle = "taVNS and pupil dilation | Bayesian living & interactive MA"),
                sidebarLayout(
                  sidebarPanel(fluidRow(
                    tabsetPanel(
                      tabPanel("Study criteria",
                               br(),
                               checkboxGroupInput(inputId = "Design", label = p("Design",style="color:#333333",
                                                                                    tags$style(type = "text/css", "#q1 {vertical-align: top;}"),
                                                                                    bsButton("q1", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),  
                                                  choices = levels(df$Design), selected = levels(df$Design)),
                               bsPopover(id="q1", title = "Study Design",
                                         content = paste0("<p>Choose to include effect sizes of studies that have a within or between participants design.",
                                                          "<p>Default: all."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               checkboxGroupInput(inputId = "Sample", label = p("Sample",style="color:#333333",
                                                                                tags$style(type = "text/css", "#q2 {vertical-align: top;}"),
                                                                                bsButton("q2", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),  
                                                  choices = levels(df$Sample), selected = levels(df$Sample)),
                               bsPopover(id="q2", title = "Sample.",
                                         content = paste0("<p>Choose to include effect sizes with healthy participants and/or different patient samples.",
                                                          "<p>Default: healthy."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                              radioButtons(inputId = "sex_yes", label = p("Select sex distribution?",style="color:#333333",
                                                                                tags$style(type = "text/css", "#q2 {vertical-align: top;}"),
                                                                                bsButton("q3a", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),  
                                                  choices = c("no","yes"), selected = "no"),
                               bsPopover(id="q3a", title = "Sample.",
                                         content = paste0("<p>Choose whether to filter for specific sex distributions. Papers without information regarding the sex-distribution will be excluded",
                                                          "<p>Default: No."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               
                               sliderInput(inputId = "gender", label = p("Percentage of Women",style="color:#333333",
                                                                         tags$style(type = "text/css", "#q3 {vertical-align: top;}"),
                                                                         bsButton("q3", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),  
                                           min = min(df$Percent.Females,na.rm = TRUE), max = max(df$Percent.Females, na.rm =TRUE), value = c(min(df$Percent.Females, na.rm =  TRUE), max(df$Percent.Females, na.rm =  TRUE)), step = 1, sep = "", ticks = F),
                               bsPopover(id="q3", title = "Percent females.",
                                         content = paste0("<p>Choose to include effect sizes with a certain percentage of female participants.",
                                                          "<p>Default: all."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                              radioButtons(inputId = "age_yes", label = p("Select average age of population?",style="color:#333333",
                                                                                 tags$style(type = "text/css", "#q2 {vertical-align: top;}"),
                                                                                 bsButton("q4a", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),  
                                                  choices = c("no","yes"), selected = "no"),
                               bsPopover(id="q4a", title = "Sample.",
                                         content = paste0("<p>Choose whether to filter for age groups (average age of the sample). Papers whithout information on the average age of the sample will be excluded",
                                                          "<p>Default: No."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               
                               sliderInput(inputId = "age", label = p("Age",style="color:#333333",
                                                                      tags$style(type = "text/css", "#q4 {vertical-align: top;}"),
                                                                      bsButton("q4", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),   
                                           min = min(df$Mean.Age, na.rm =  TRUE), max = max(df$Mean.Age, na.rm =  TRUE), value = c(min(df$Mean.Age, na.rm =  TRUE), max(df$Mean.Age, na.rm =  TRUE)), step = 1, sep = "", ticks = F),
                               bsPopover(id="q4", title = "Age.",
                                         content = paste0("<p>Choose to include effect sizes with a certain mean age of participants.",
                                                          "<p>Default: all."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               checkboxGroupInput(inputId = "blind", label = p("Blindness",style="color:#333333",
                                                                                tags$style(type = "text/css", "#q5 {vertical-align: top;}"),
                                                                                bsButton("q5", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),  
                                                  choices = levels(df$Blindness), selected = levels(df$Blindness)),
                               bsPopover(id="q5", title = "Blindness.",
                                         content = paste0("<p>Choose to include double-blind, single-blind and/or open label studies.",
                                                          "<p>Default: all"),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               checkboxGroupInput(inputId = "rob", label = p("Risk of bias",style="color:#333333",
                                                                               tags$style(type = "text/css", "#q6 {vertical-align: top;}"),
                                                                               bsButton("q6", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),  
                                                  choices = levels(df$risk_of_bias), selected = levels(df$risk_of_bias)),
                               bsPopover(id="q6", title = "Risk of bias.",
                                         content = paste0("<p>Choose to include studies with low risk, some concerns, high risk of bias.",
                                                          "<p>Default: all"),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                              sliderInput(inputId = "pubyear", label = p("Publication year",style="color:#333333",
                                                                         tags$style(type = "text/css", "#q7 {vertical-align: top;}"),
                                                                         bsButton("q7", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),
                                          min = min(df$Publication.Year), max = max(df$Publication.Year), value = c(min(df$Publication.Year), max(df$Publication.Year)), step = 1, sep = "", ticks = F),
                              bsPopover(id="q7", title = "Publication year.",
                                        content = paste0("<p>Choose to include effect sizes from studies with a certain range of publication years.",
                                                         "<p>Default: all."),
                                         placement = "right",
                                         trigger = "click",
                                         options = list(container = "body")),
                               checkboxGroupInput(inputId = "included", label = p("Include/exclude specific studies",style="color:#333333",
                                                               tags$style(type = "text/css", "#q8 {vertical-align: top;}"),
                                                                                  bsButton("q8", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),
                                                  choices = levels(df$study), selected = levels(df$study)),
                               bsPopover(id="q8", title = "Include/exclude specific studies.",
                                         content = paste0("<p>Exclude specific studies by removing the tick mark.",
                                                          "<p>This selection is hierarchically below the other inclusion/exclusion criteria.",
                                                          "<p>If for example Villani (2022) is excluded, because studies recording pupil size with a Tobii device are not selected for inclusion above, this study will not be included in the analysis, even though it is still ticked here.",
                                                          "<p>However, if studies recording pupil size with a Tobii device are selected for inclusion above, but Villani (2022) is unticked here, the study will not be included."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body"))),
                      tabPanel("taVNS specifications",
                               br(), checkboxGroupInput(inputId = "stimtype", label = p("Stimulation Type",style="color:#333333",
                                                                                         tags$style(type = "text/css", "#q9 {vertical-align: top;}"),
                                                                                         bsButton("q9", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")), 
                                                        choices = levels(df$Stimulation.Type), selected = levels(df$Stimulation.Type)),
                               bsPopover(id="q9", title = "Stimulation Type.",
                                         content = paste0("<p>Choose to include conventional or pulsed stimulation, or both.",
                                                          "<p>Default: all."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               checkboxGroupInput(inputId = "stimside", label = p("Stimulation Side",style="color:#333333",
                                                                                      tags$style(type = "text/css", "#q10 {vertical-align: top;}"),
                                                                                      bsButton("q10", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),  
                                                  choices = levels(df$Stimulation.side), selected = levels(df$Stimulation.side)),
                               bsPopover(id="q10", title = "Side of the stimulated ear.",
                                         content = paste0("<p>Choose to include studies using left or right stimulation, or both.",
                                                          "<p>Default: all."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               sliderInput(inputId = "stimduration", label = p("Duration of one uninterrupted stimulation pulse (in sec.)",style="color:#333333",
                                                                              tags$style(type = "text/css", "#q11 {vertical-align: top;}"),
                                                                              bsButton("q11", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),  
                                           min = min(df$Stimulation.time), max = max(df$Stimulation.time), value = c(min(df$Stimulation.time), max(df$Stimulation.time)), step = 10, sep = "", ticks = F),
                               bsPopover(id="q11", title = "Stimulation duration (in sec.).",
                                         content = paste0("<p>Choose to include effect sizes from studies that stimulated the vagus nerve with a specific length of uninterrupted stimulation. Pulsed protocols have stimulation pulse duration <= 5s, conventional stimulation up to 3000s for monophasic stimulation",
                                                          "<p>Default: all."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               checkboxGroupInput(inputId = "partear", label = p("part of the ear stimulated",style="color:#333333",
                                                                                    tags$style(type = "text/css", "#q12 {vertical-align: top;}"),
                                                                                    bsButton("q12", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),   
                                                  choices = levels(df$Part.of.the.ear.stimulated), selected = levels(df$Part.of.the.ear.stimulated)),
                               bsPopover(id="q12", title = "Part of the ear stimulated.",
                                         content = paste0("<p>Choose to include effect sizes from studies that stimulate different parts of the ear.",
                                                          "<p>Default: all."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               checkboxGroupInput(inputId = "device", label = p("taVNS device",style="color:#333333",
                                                                                 tags$style(type = "text/css", "#q13 {vertical-align: top;}"),
                                                                                 bsButton("q13", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),   
                                                  choices = levels(df$taVNS.Device), selected = levels(df$taVNS.Device)),
                               bsPopover(id="q13", title = "taVNS device.",
                                         content = paste0("<p>Choose to include effect sizes from studies using specific taVNS devices.",
                                                          "<p>Default: all."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               checkboxGroupInput(inputId = "intensitytype", label = p("Stimulation intensity method",style="color:#333333",
                                                                                 tags$style(type = "text/css", "#q14 {vertical-align: top;}"),
                                                                                 bsButton("q14", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),   
                                                  choices = levels(df$Intensity.fixed.or.matched), selected = levels(df$Intensity.fixed.or.matched)),
                               bsPopover(id="q14", title = "Determined intensity.",
                                         content = paste0("<p>Choose to include effect sizes from studies with a fixed intensity for sham and tVNS or with a sensation matched intensity or other (e.g., unsuccesful matching, only one condition calibrated).",
                                                          "<p>Default: all."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               sliderInput(inputId = "impulsefreq", label = p("Stimulation frequency (in Hz)",style="color:#333333",
                                                                               tags$style(type = "text/css", "#q15 {vertical-align: top;}"),
                                                                               bsButton("q15", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),  
                                           min = min(df$`Impulse.frequency (Hz)`), max = max(df$`Impulse.frequency (Hz)`), value = c(min(df$`Impulse.frequency (Hz)`), max(df$`Impulse.frequency (Hz)`)), step = 10, sep = "", ticks = F),
                               bsPopover(id="q15", title = "Stimulation frequency (in Hz).",
                                         content = paste0("<p>Choose to include effect sizes from studies that applied specific stimulation frequencies.",
                                                          "<p>Default: all."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               checkboxGroupInput(inputId = "eyeside", label = p("side of the recorded eye",style="color:#333333",
                                                                                 tags$style(type = "text/css", "#q16 {vertical-align: top;}"),
                                                                                 bsButton("q16", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),   
                                                  choices = levels(df$Eye.Side.Measured), selected = levels(df$Eye.Side.Measured)),
                               bsPopover(id="q16", title = "Side of the recorded eye.",
                                         content = paste0("<p>Choose to include effect sizes from studies that record the left, the right or both eyes.",
                                                          "<p>Default: all."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               checkboxGroupInput(inputId = "task", label = p("task-related recording",style="color:#333333",
                                                                                 tags$style(type = "text/css", "#q17 {vertical-align: top;}"),
                                                                                 bsButton("q17", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),   
                                                  choices = levels(df$Task.related), selected = levels(df$Task.related)),
                               bsPopover(id="q17", title = "Was the recording during a task or not.",
                                         content = paste0("<p>Choose to include effect sizes from studies that stimulate at different stages of a task.",
                                                          "<p>Default: all."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               checkboxGroupInput(inputId = "dilationtype", label = p("pupil dilation type",style="color:#333333",
                                                                                 tags$style(type = "text/css", "#q18 {vertical-align: top;}"),
                                                                                 bsButton("q18", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),   
                                                  choices = levels(df$Pupil.Dilation.Type), selected = levels(df$Pupil.Dilation.Type)),
                               bsPopover(id="q18", title = "Type of recorded pupil dilation.",
                                         content = paste0("<p>Choose to include effect sizes from studies that record the phasic, tonic, phasic-like or event-related pupil dilation.",
                                                          "<p>Default: all."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               checkboxGroupInput(inputId = "eyetracker", label = p("eye tracking device",style="color:#333333",
                                                                                 tags$style(type = "text/css", "#q19 {vertical-align: top;}"),
                                                                                 bsButton("q19", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),   
                                                  choices = levels(df$Eye.Tracker.Device), selected = levels(df$Eye.Tracker.Device)),
                               bsPopover(id="q19", title = "Eye-tracker device.",
                                         content = paste0("<p>Select studies with a specific type of eye-tracker.",
                                                          "<p>Default: all."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               checkboxGroupInput(inputId = "light", label = p("ambient light",style="color:#333333",
                                                                                 tags$style(type = "text/css", "#q20 {vertical-align: top;}"),
                                                                                 bsButton("q20", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),   
                                                  choices = levels(df$Ambient.Light.Yes.or.No), selected = levels(df$Ambient.Light.Yes.or.No)),
                               bsPopover(id="q20", title = "Level of ambient light.",
                                         content = paste0("<p>Choose to include effect sizes from studies that record in darkness or light.",
                                                          "<p>Default: all."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               checkboxGroupInput(inputId = "control", label = p("Control type",style="color:#333333",
                                                                                  tags$style(type = "text/css", "#q21 {vertical-align: top;}"),
                                                                                  bsButton("q21", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")), 
                                                  choices = levels(df$Control.Type), selected = c("earlobe sham", "scapha sham")),
                               bsPopover(id="q21", title = "Control type",
                                         content = paste0("<p>Choose to include effect sizes with different types of control stimulation.")),
                               placement = "right", 
                               trigger = "click",
                               options = list(container = "body")),
                      tabPanel("Prior specifications",
                               br(), numericInput(inputId = "mupriormean", label = p("µ prior mean",style="color:#333333",
                                                                                     tags$style(type = "text/css", "#q22 {vertical-align: top;}"),
                                                                                     bsButton("q22", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),   
                                                  value = 0, step = 0.1),
                               bsPopover(id="q22", title = "µ prior mean.",
                                         content = paste0("<p>Set the mean of your µ prior (effect).",
                                                          "<p>Note that the results and their interpretability are drastically influenced by prior choices.",
                                                          "<p>Default: 0"),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               numericInput(inputId = "mupriorsd", label = p("µ prior standard deviation", style="color:#333333",
                                                                             tags$style(type = "text/css", "#q23 {vertical-align: top;}"),
                                                                             bsButton("q23", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),    
                                            value = 1.5, step = 0.1, min = 0),
                               bsPopover(id="q23", title = "µ prior standard deviation.",
                                         content = paste0("<p>Set the standard deviation of your µ prior (effect).",
                                                          "<p>Note that the results and their interpretability are drastically influenced by prior choices.",
                                                          "<p>Default: 1.5"),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               radioButtons(inputId = "robust", label = p("µ Bayes Factor robustness check", style="color:#333333",
                                                                          tags$style(type = "text/css", "#q24 {vertical-align: top;}"),
                                                                          bsButton("24", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),    
                                            choices = c(No = "No", Yes = "Yes")),
                               bsPopover(id="q24", title = "µ Bayes Factor robustness check.",
                                         content = paste0("<p>Bayes Factors over a variety of prior standard deviations will be plotted.",
                                                          "<p>Note that selecting Yes will lead to an increase in computation time and that the plot will only be computed if priors for τ and μ are proper.",
                                                          "<p>Default: No."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               radioButtons(inputId = "tauprior", label = p("τ prior", style="color:#333333",
                                                                            tags$style(type = "text/css", "#q25 {vertical-align: top;}"),
                                                                            bsButton("q25", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),    
                                            choices = c("Half cauchy", "Half student t","uniform", "sqrt", "Jeffreys", "BergerDeely", "conventional", "DuMouchel", "shrinkage", "I2")),
                               bsPopover(id="q25", title = "τ prior.",
                                         content = paste0("<p>Choose your τ prior.",
                                                          "<p>Note that the results and their interpretability are drastically influenced by prior choices.",
                                                          "<p>Default: Half cauchy."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               numericInput(inputId="scaletau", label = p("τ prior scale (for half cauchy or half student t)",style="color:#333333",
                                                                          tags$style(type = "text/css", "#q26 {vertical-align: top;}"),
                                                                          bsButton("q26", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),    
                                            value=0.5, step=0.05),
                               bsPopover(id="q26", title = "τ prior scale.",
                                         content = paste0("<p>Set the scale of your τ prior (if a half cauchy or a half student t prior is selected).",
                                                          "<p>Note that the results and their interpretability are drastically influenced by prior choices.",
                                                          "<p>Default: 0.5"),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               a("Further information on choosing an appropriate τ prior.", href="https://cran.r-project.org/web/packages/bayesmeta/bayesmeta.pdf", target = "_blank")),
                      tabPanel("Meta-Regression",
                               br(),    radioButtons(inputId = "MetaReg", label = p("Meta-Regression", style="color:#333333",
                                                                                                               tags$style(type = "text/css", "#q27 {vertical-align: top;}"),
                                                                                                               bsButton("q27", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),    
                                                     choices = c(No = "No", Yes = "Yes")),
                               bsPopover(id="q27", title = "Meta-Regression",
                                         content = paste0("<p>Choose if any regressions with covariates should be calculated.",
                                                          "<p>Note that at the moment not all coded variables are available for the Meta-regression.",
                                                          "<p>Default: No."),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               checkboxGroupInput(inputId = "Predictors", label = p("Predictors",style="color:#333333",
                                                                                           tags$style(type = "text/css", "#q16 {vertical-align: top;}"),
                                                                                           bsButton("q28", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),   
                                                            choices = c("Stimulation type","Risk of bias","Sensation-matching","Task-related (rest vs. task)","Stimulation intensity (tVNS)","Stimulation intensity (tVNS-sham)","Stimulation length (pulsed stimulation only)","Stimulation frequency","Pupil size outcome (tonic vs. phasic, for conventional stimulation only)"), selected = "Stimulation type"),
                                         bsPopover(id="q28", title = "Side of the recorded eye.",
                                                   content = paste0("<p>Choose which meta-regressions should be calculated based on the current inclusion and exclusion criteria. Note that some options can only be calculated for subgroups of the data (e.g., only studies using brief stimulation pulses) as not enough studies for the other protocols are available.",
                                                                    "<p>Default: Stimulation type."),
                                                   placement = "right", 
                                                   trigger = "click",
                                                   options = list(container = "body"))),
                      hr(),
                      submitButton("Re-Calculate Meta-Analysis", icon("sync"))
                    ))),
                mainPanel(
                  fluidRow(
                  tabsetPanel(
                    tabPanel("Explanation", br(),
                             h3("Welcome to the living & interactive meta-analysis on the influence of taVNS on pupil dilation."), br(),
                             h4("Purpose:"),
                             ("Transcutaneous Vagus Nerve Stimulation (tVNS) has emerged as a promising technique to modulate autonomic functions, and pupil dilation has been recognized as a promising biomarker for tVNS-driven monoaminergic release. Nevertheless, recent studies on the effectiveness of tVNS protocols have produced heterogeneous results. The aim of this meta-analysis is therefore to syntethize the existing evidence and provide a comparison between pulsed and continuos stimulation protocols. Comparable to our previous meta-analysis on tVNS-induced changes in "),
                             a("HRV", href="https://neuromadlab.shinyapps.io/taVNSHRVmeta/", target = "_blank"),
                             (", we perform a living Bayesian random effects meta-analysis to synthesize the current evidence concerning the effects of different taVNS protocols on pupil dilation. To keep the synthesis of evidence transparent and up to date as new studies are being published, we developed a Shiny web app that regularly incorporates new results and enables users to modify study selection criteria to evaluate the robustness of the inference across potential confounds. By increasing transparency and timeliness, we believe that the concept of living meta-analyses can lead to transformational benefits in emerging fields."), br(),
                             h4("Explanation:"),
                             p("Select inclusion criteria and prior settings in the panel on the left. Click 'Re-Calculate Meta-Analysis' to rerun the analysis. Results are displayed in the central panels."), br(),
                             h4("Paper:"),
                             ("This app accompanies the following "),
                             a("paper", href="ADD PAPER DOI", target = "_blank"), 
                             ("where a more detailed explanation and an exemplary analysis can be found. Inclusion criteria and prior settings of the exemplary analysis correspond to this app's default criteria."), br(), br(),
                             h4("Code and data:"),
                             ("This app's R Code and datasets can be found "),
                             a("here", href="https://github.com/neuromadlab/taVNSpupilmeta", target = "_blank"),
                             ("on GitHub."), br(), br(),
                             h4("Adding new results:"),
                             p("A living meta-analysis means a growing meta-analysis. Therefore, if we either missed a paper, you published results which are not yet shown in the 'Full texts screened'-table or you have unpublished data of your experiments, please contact us."), br(), br(),
                             h4("Contact:"),
                             p("The app is maintained by neuroMADLAB (Neuroscience of Motivation, Action, & Desire) at the University of Bonn and Tuebingen, Germany."),
                             p("Contact/Visit us:"),
                             a(shiny::actionButton(inputId = "email1", 
                                                   label = "Mail", 
                                                   icon = icon("envelope", lib = "font-awesome")),
                               href="mailto:neuromadlab@klinikum.uni-tuebingen.de"),
                             a(shiny::actionButton(inputId = "website", 
                                                   label = "Web", 
                                                   icon = icon("globe", lib = "font-awesome")),
                               href="http://www.neuromadlab.com"),
                             a(shiny::actionButton(inputId = "website", 
                                                   label = "Twitter", 
                                                   icon = icon("twitter", lib = "font-awesome")),
                               href="http://www.twitter.com/neuromadlab")
                    ),
                    tabPanel("Studies overview", br(),
                             h4("This table provides an overview of the studies included in the analysis:"),
                             textOutput("warning"), br(),
                             DT::dataTableOutput("study") %>% withSpinner(type = 6, color = "#3498DB"), br(),#changed on 31.01.2024 (from studies)
                             h4("Abbreviations:"), 
                             p("taVNS: transcutaneous auricular vagus nerve stimulation."),
                             p("ERPD: event-related pupil dilation.")),
                    tabPanel("Outlier check", br(),
                             h4("Boxplot graph:"), plotOutput("boxplot") %>% withSpinner(type = 6, color = "#3498DB")),
                    tabPanel("Forest plot", br(),
                             h4("Forest plot with 95% credible intervals:"),
                             plotOutput("forest") %>% withSpinner(type = 6, color = "#3498DB")),
                    tabPanel("Funnel plot", br(),
                             h4("Funnel plot to assess publication bias:"),
                             plotOutput("funnel")  %>% withSpinner(type = 6, color = "#3498DB")),
                    tabPanel("Statistics", br(),
                             h4("Parameters:"),
                             p("τ (tau): posterior distribution of heterogeneity."),
                             p("μ (mu): posterior distribution of effect."),
                             p("θ (theta): 'predictive distribution, that expresses the posterior knowledge about a future observation, i.e., an additional draw θk+1 from the underlying population of studies.' (Röver, 2020, p. 16)."),
                             ("Statistics are calculated/estimated using the bayesmeta package "), 
                             a("(Röver, 2020).", href="http://dx.doi.org/10.18637/jss.v093.i06", target = "_blank"),
                             ("The corresponding github page can be found "),
                             a("here.", href = "https://github.com/cran/bayesmeta", target = "_blank"), br(),
                             h4("Bayes factors:"), verbatimTextOutput("bf") %>% withSpinner(type = 6, color = "#3498DB"),
                             p("Bayes factors are only computed if the priors for τ and μ are proper."), br(),
                             h4("Marginal posterior summary:"), verbatimTextOutput("summary") %>% withSpinner(type = 6, color = "#3498DB"), br(),
                             h4("Maximum-likelihood:"), verbatimTextOutput("ML") %>% withSpinner(type = 6, color = "#3498DB"), br(),
                             h4("Joint maximum-a-posteriori:"), verbatimTextOutput("MAP") %>% withSpinner(type = 6, color = "#3498DB")),
                    tabPanel("Full texts screened", br(),
                             h4("This table provides an overview of all full-text we assessed for eligibility:"),
                             DT::dataTableOutput("screened") %>% withSpinner(type = 6, color = "#3498DB"), br(),
                             h4("Adding new results:"),
                             ("A living meta-analysis means a growing meta-analysis. Therefore, if we either missed a paper, you published results which are not yet shown in this table or you have unpublished pupil dilation data of your taVNS experiments, please"),
                             a("contact us.", href="mailto:neuromadlab@klinikum.uni-tuebingen.de", target = "_blank")),
                    tabPanel("Additional plots", br(),
                             h4("Joint posterior density of heterogeneity τ and effect μ:"), plotOutput("joint") %>%  withSpinner(type = 6, color = "#3498DB"),
                             p("Darker shading corresponds to higher probability density."),
                             p("Red lines indicate (approximate) 2-dimensional credible regions,"),
                             p("green lines show marginal posterior medians and 95% credible intervals,"),
                             p("blue lines show conditional posterior mean effect as a function of the heterogeneity along with a 95% interval."),
                             p("Red cross (+): posterior mode"),
                             p("Pink cross (x): ML estimate"), br(),
                             h4("Prior, posterior, & likelihood:"), plotOutput("evupdate") %>% withSpinner(type = 6, color = "#3498DB"), br(),
                             h4("τ prior distribution:"), plotOutput("taupriorplot") %>% withSpinner(type = 6, color = "#3498DB")),
                    tabPanel("Bayes factor robustness check", br(),
                             h4("Bayes Factors over a variety of prior standard deviations:"),
                             p("Will only be computed if 'Yes' is selected for 'µ Bayes Factor robustness check' and the priors for τ and μ are proper."),br(),
                             conditionalPanel(condition = "input.tauprior == 'uniform' | 
                                                               input.tauprior == 'sqrt' |
                                                               input.tauprior == 'Jeffreys' |
                                                               input.tauprior == 'BergerDeely' | 
                                                               input.tauprior == 'conventional' | 
                                                               input.tauprior == 'DuMouchel' | 
                                                               input.tauprior == 'shrinkage' | 
                                                               input.tauprior == 'I2'",
                                              textOutput("warning2")),
                             conditionalPanel(condition = "input.robust == 'Yes'", 
                                              plotOutput("robustplot") %>% withSpinner(type = 6, color = "#3498DB"),
                                              p("Default: 1.5 (orange horizontal line)"),
                                              p("Narrow: user selected standard deviation / 2"),
                                              p("User: user selected standard deviation"),
                                              p("Wide: user selected standard deviation + 1"),
                                              p("Ultrawide: user selected standard deviation + 2"),
                                              p("Interpretations of Bayes factors are based on Jeffreys (1961) with slight modifications by Lee and Wagenmakers (2013) and should be considered with caution."))),
                    tabPanel("Meta-Regression", br(),
                             h4("Calculates separate meta-regressions for the selected studies and factors:"),
                             p("Will only be computed if 'Yes' is selected for 'Meta-Regression'"),br(),
                             conditionalPanel(condition = "input.MetaReg == 'No'",
                                              textOutput("warning3")),
                             conditionalPanel(condition = "'Stimulation type' %in% input.Predictors", 
                                              plotOutput("metareg_stimtype") %>% withSpinner(type = 6, color = "#3498DB"),
                                              p("Comparison of studies using brief stimulation pulses vs. long-lasting stimulation protocols")),
                             conditionalPanel(condition = "'Risk of bias' %in% input.Predictors", 
                                              plotOutput("metareg_rob") %>% withSpinner(type = 6, color = "#3498DB"),
                                              p("Comparison of studies with a high risk of bias vs. studies with a low risk or only some concerns")),
                             conditionalPanel(condition = "'Pupil size outcome (tonic vs. phasic, for conventional stimulation only)' %in% input.Predictors", 
                                              plotOutput("metareg_pupilout") %>% withSpinner(type = 6, color = "#3498DB"),
                                              p("Comparison between tVNS effects on tonic vs. phasic responses for conventional stimulation")),
                             conditionalPanel(condition = "'Sensation-matching' %in% input.Predictors", 
                                              plotOutput("metareg_sensmatch") %>% withSpinner(type = 6, color = "#3498DB"),
                                              p("Comparison of studies matching sham and tVNS stimulation intensity by matching the sensation vs. studies not applying this approach successfully")),
                             conditionalPanel(condition = "'Task-related (rest vs. task)' %in% input.Predictors", 
                                              plotOutput("metareg_task") %>% withSpinner(type = 6, color = "#3498DB"),
                                              p("Comparison of pupil dilation outcomes vs. the effects of tVNS on task-related pupil outcomes including oddball tasks and the pupillary light reflex")),
                             conditionalPanel(condition = "'Stimulation length (pulsed stimulation only)' %in% input.Predictors", 
                                              plotOutput("metareg_stimlength") %>% withSpinner(type = 6, color = "#3498DB"),
                                              p("Effect of the length of stimulation pulses in the brief stimulation condition on the phasic pupil response")),
                             conditionalPanel(condition = "'Stimulation frequency' %in% input.Predictors", 
                                              plotOutput("metareg_stimfreq") %>% withSpinner(type = 6, color = "#3498DB"),
                                              p("Effect of stimulation frequency parameter on pupil response")),
                             conditionalPanel(condition = "'Stimulation intensity (tVNS-sham)' %in% input.Predictors", 
                                              plotOutput("metareg_stimintensitydiff", width = 1200, height = 700) %>% withSpinner(type = 6, color = "#3498DB"),
                                              p("Effect of stimulation intensity difference between sham and tVNS")),
                             conditionalPanel(condition = "'Stimulation intensity (tVNS)' %in% input.Predictors", 
                                              plotOutput("metareg_stimintensity") %>% withSpinner(type = 6, color = "#3498DB"),
                                              p("Effect of stimulation intensity in the tVNS condition"))),
                    
                  )
                )
                )
                )
)


                  